name: DummyFront

on:
  push:
    branches:
      - master
      - feature/github_actions
      paths:
        - 'dummyFront/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!